### ISSUE TITLE
About the Endovis18 dataset

### ISSUE THREAD

**Issue by wangtong627** [CityU-AIM-Group/JCAS#1]
Wonderful work!
We try to run this model, but we can not find the dataset Endovis18 ('/home/xiaoqiguo2/OpensetNTM_instru/instrument/Endovis18/')
Could you apply the access or url of this dataset?
Thanks!

**Comment by Guo-Xiaoqing** [comment]
> 

The data can be found at https://endovissub2018-roboticscenesegmentation.grand-challenge.org/
The corresponding paper can be found at https://arxiv.org/pdf/2001.11190.pdf

**Comment by wangtong627** [comment]
Thanks for your help
